version: '3.1'

services:

  data:
    container_name: symfony-graphql-data
    build: docker/data
    volumes:
      - ./application:/var/www/html
    command: /var/local/entrypoint.sh
    networks:
      - internal

  php-fpm:
    build: docker/php-fpm
    container_name: symfony-graphql-php-fpm
    working_dir: /var/www/html
    volumes:
      - ./application:/var/www/html
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - internal

  mysql:
    image: mysql:8.0
    container_name: symfony-graphql-mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./docker/mysqldata:/var/lib/mysql
      - ./docker/mysql-files:/var/lib/mysql-files
    ports:
      - "3306:3306"
    networks:
      - internal

  webserver:
    image: nginx:alpine
    container_name: symfony-graphql-webserver
    working_dir: /var/www/html
    links:
      - php-fpm
      - mysql
    volumes:
      - ./application:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - internal


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3307
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - internal

networks:
  internal: